### ISSUE TITLE
Adding i2p support?

### ISSUE THREAD

**Issue by eyedeekay** [d4l3k/wikigopher#1]
I've got this library/application called [https://github.com/eyedeekay/sam-forwarder](sam-forwarder) which makes it very easy to add [i2p](https://geti2p.net) configuration to web application written in Go. I'd like to make this capability available(and let people self-host wikipedia mirrors on i2p). I have done this for example in my [fork](https://github.com/d4l3k/wikigopher/compare/master...eyedeekay:master). As you can see the changes are not extensive, but one in particular I'd like to call your attention to on 399 of my fork is that in the presence of an i2p configuration, the host and port in the i2p configuration will override the host and port passed at the terminal. This is intended to prevent the user from accidentally listening on unintended addresses/ports when configuring for i2p, but if that approach is unacceptable I can work around it.

**Comment by d4l3k** [comment]
Hey, thanks for your interest! 

I'd prefer to not tie this code to specific transport layers. If you wanted to provide this via i2p, I'd recommend using a reverse proxy like strategy (i.e. same way nginx works).
